apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: heart-disease
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: heart-disease-api
        metrics_path: /metrics
        static_configs:
          - targets:
              - heart-disease-api.heart-disease.svc:80
